"""Dati statici dei circuiti e Calendario 2026 (FOR-8).

Il motore e' puro (ADR 0002) e non legge dal database: i 24 circuiti del
Calendario 2026 vivono qui come dataclass immutabili. supabase/seed.sql
e' il mirror SQL di questi stessi valori per la persistenza: ogni
modifica ai numeri va riportata in entrambi i posti.

Il tempo base sul giro (secondi), i pesi sui 6 Attributi vettura
(0.0-1.0), la severita' gomme (1-5), la difficolta' di sorpasso (1-5),
le probabilita' di Safety car e pioggia e le mescole nominate sono
valori di partenza plausibili, da tarare con l'harness di bilanciamento
(T2.4.1).
"""

from dataclasses import dataclass
from datetime import date

# How much each of the 6 car attributes counts on the lap, keyed by the
# attribute names of fm_engine.world.models.CAR_ATTRIBUTES.
_WEIGHT_FIELDS: tuple[str, ...] = (
    "engine_power_weight",
    "downforce_weight",
    "aero_efficiency_weight",
    "mechanical_grip_weight",
    "tyre_management_weight",
    "reliability_weight",
)


@dataclass(frozen=True)
class Circuit:
    """Un circuito del Calendario, con profilo prestazionale e ambientale.

    Replica la riga della tabella SQL circuits: pesi sugli Attributi
    vettura, severita' gomme, probabilita' Safety car, profilo meteo e
    le 3 Mescole nominate per il GP.
    """

    code: str
    name: str
    country: str
    locality: str
    length_metres: int
    race_laps: int
    calendar_order: int
    race_date_2026: date
    weekend_format_2026: str
    # Realistic reference race lap of the base season, in seconds: the
    # additive base of the lap time model (fm_engine.laptime).
    base_lap_seconds: float
    engine_power_weight: float
    downforce_weight: float
    aero_efficiency_weight: float
    mechanical_grip_weight: float
    tyre_management_weight: float
    reliability_weight: float
    tyre_severity: int
    # Overtaking difficulty on track, scale 1 (easy: Monza) - 5 (nearly
    # impossible: Monaco). Modulates duel resolution in the race engine.
    overtaking_difficulty: int
    safety_car_probability: float
    weather_profile: str
    rain_probability: float
    hard_compound: str
    medium_compound: str
    soft_compound: str

    @property
    def attribute_weights(self) -> dict[str, float]:
        """I pesi del circuito indicizzati per nome di Attributo vettura."""
        return {
            attribute: getattr(self, field)
            for attribute, field in zip(
                (
                    "engine_power",
                    "downforce",
                    "aero_efficiency",
                    "mechanical_grip",
                    "tyre_management",
                    "reliability",
                ),
                _WEIGHT_FIELDS,
                strict=True,
            )
        }

    @property
    def nominated_compounds(self) -> tuple[str, str, str]:
        """Le 3 Mescole da asciutto nominate, dalla piu' dura alla piu' morbida."""
        return (self.hard_compound, self.medium_compound, self.soft_compound)


# The 24 circuits of the 2026 calendar (original 2025 announcement,
# Bahrain and Jeddah included), in calendar order. Values mirrored in
# supabase/seed.sql.
CALENDAR_2026: tuple[Circuit, ...] = (
    Circuit(
        code="albert_park",
        name="Albert Park Circuit",
        country="Australia",
        locality="Melbourne",
        length_metres=5278,
        race_laps=58,
        calendar_order=1,
        race_date_2026=date(2026, 3, 8),
        weekend_format_2026="standard",
        base_lap_seconds=80.0,
        engine_power_weight=0.70,
        downforce_weight=0.75,
        aero_efficiency_weight=0.65,
        mechanical_grip_weight=0.75,
        tyre_management_weight=0.65,
        reliability_weight=0.60,
        tyre_severity=3,
        overtaking_difficulty=3,
        safety_car_probability=0.40,
        weather_profile="variable",
        rain_probability=0.25,
        hard_compound="C3",
        medium_compound="C4",
        soft_compound="C5",
    ),
    Circuit(
        code="shanghai",
        name="Shanghai International Circuit",
        country="Cina",
        locality="Shanghai",
        length_metres=5451,
        race_laps=56,
        calendar_order=2,
        race_date_2026=date(2026, 3, 15),
        weekend_format_2026="sprint",
        base_lap_seconds=95.0,
        engine_power_weight=0.75,
        downforce_weight=0.75,
        aero_efficiency_weight=0.70,
        mechanical_grip_weight=0.65,
        tyre_management_weight=0.80,
        reliability_weight=0.60,
        tyre_severity=4,
        overtaking_difficulty=2,
        safety_car_probability=0.30,
        weather_profile="variable",
        rain_probability=0.30,
        hard_compound="C2",
        medium_compound="C3",
        soft_compound="C4",
    ),
    Circuit(
        code="suzuka",
        name="Suzuka International Racing Course",
        country="Giappone",
        locality="Suzuka",
        length_metres=5807,
        race_laps=53,
        calendar_order=3,
        race_date_2026=date(2026, 3, 29),
        weekend_format_2026="standard",
        base_lap_seconds=92.0,
        engine_power_weight=0.70,
        downforce_weight=0.90,
        aero_efficiency_weight=0.75,
        mechanical_grip_weight=0.70,
        tyre_management_weight=0.80,
        reliability_weight=0.65,
        tyre_severity=4,
        overtaking_difficulty=4,
        safety_car_probability=0.25,
        weather_profile="variable",
        rain_probability=0.30,
        hard_compound="C1",
        medium_compound="C2",
        soft_compound="C3",
    ),
    Circuit(
        code="sakhir",
        name="Bahrain International Circuit",
        country="Bahrein",
        locality="Sakhir",
        length_metres=5412,
        race_laps=57,
        calendar_order=4,
        race_date_2026=date(2026, 4, 12),
        weekend_format_2026="standard",
        base_lap_seconds=93.0,
        engine_power_weight=0.80,
        downforce_weight=0.65,
        aero_efficiency_weight=0.70,
        mechanical_grip_weight=0.75,
        tyre_management_weight=0.85,
        reliability_weight=0.75,
        tyre_severity=4,
        overtaking_difficulty=2,
        safety_car_probability=0.30,
        weather_profile="dry",
        rain_probability=0.05,
        hard_compound="C1",
        medium_compound="C2",
        soft_compound="C3",
    ),
    Circuit(
        code="jeddah",
        name="Jeddah Corniche Circuit",
        country="Arabia Saudita",
        locality="Jeddah",
        length_metres=6174,
        race_laps=50,
        calendar_order=5,
        race_date_2026=date(2026, 4, 19),
        weekend_format_2026="standard",
        base_lap_seconds=91.0,
        engine_power_weight=0.85,
        downforce_weight=0.70,
        aero_efficiency_weight=0.85,
        mechanical_grip_weight=0.65,
        tyre_management_weight=0.60,
        reliability_weight=0.70,
        tyre_severity=2,
        overtaking_difficulty=2,
        safety_car_probability=0.60,
        weather_profile="dry",
        rain_probability=0.05,
        hard_compound="C2",
        medium_compound="C3",
        soft_compound="C4",
    ),
    Circuit(
        code="miami",
        name="Miami International Autodrome",
        country="Stati Uniti",
        locality="Miami",
        length_metres=5412,
        race_laps=57,
        calendar_order=6,
        race_date_2026=date(2026, 5, 3),
        weekend_format_2026="sprint",
        base_lap_seconds=91.0,
        engine_power_weight=0.80,
        downforce_weight=0.70,
        aero_efficiency_weight=0.75,
        mechanical_grip_weight=0.70,
        tyre_management_weight=0.75,
        reliability_weight=0.70,
        tyre_severity=3,
        overtaking_difficulty=3,
        safety_car_probability=0.45,
        weather_profile="variable",
        rain_probability=0.30,
        hard_compound="C2",
        medium_compound="C3",
        soft_compound="C4",
    ),
    Circuit(
        code="montreal",
        name="Circuit Gilles Villeneuve",
        country="Canada",
        locality="Montreal",
        length_metres=4361,
        race_laps=70,
        calendar_order=7,
        race_date_2026=date(2026, 5, 24),
        weekend_format_2026="sprint",
        base_lap_seconds=76.0,
        engine_power_weight=0.85,
        downforce_weight=0.60,
        aero_efficiency_weight=0.75,
        mechanical_grip_weight=0.80,
        tyre_management_weight=0.70,
        reliability_weight=0.75,
        tyre_severity=3,
        overtaking_difficulty=2,
        safety_car_probability=0.50,
        weather_profile="variable",
        rain_probability=0.35,
        hard_compound="C3",
        medium_compound="C4",
        soft_compound="C5",
    ),
    Circuit(
        code="monaco",
        name="Circuit de Monaco",
        country="Monaco",
        locality="Monte Carlo",
        length_metres=3337,
        race_laps=78,
        calendar_order=8,
        race_date_2026=date(2026, 6, 7),
        weekend_format_2026="standard",
        base_lap_seconds=74.0,
        engine_power_weight=0.40,
        downforce_weight=0.90,
        aero_efficiency_weight=0.40,
        mechanical_grip_weight=0.95,
        tyre_management_weight=0.55,
        reliability_weight=0.70,
        tyre_severity=1,
        overtaking_difficulty=5,
        safety_car_probability=0.65,
        weather_profile="variable",
        rain_probability=0.20,
        hard_compound="C3",
        medium_compound="C4",
        soft_compound="C5",
    ),
    Circuit(
        code="barcellona",
        name="Circuit de Barcelona-Catalunya",
        country="Spagna",
        locality="Montmelo",
        length_metres=4657,
        race_laps=66,
        calendar_order=9,
        race_date_2026=date(2026, 6, 14),
        weekend_format_2026="standard",
        base_lap_seconds=77.0,
        engine_power_weight=0.65,
        downforce_weight=0.85,
        aero_efficiency_weight=0.70,
        mechanical_grip_weight=0.70,
        tyre_management_weight=0.85,
        reliability_weight=0.60,
        tyre_severity=4,
        overtaking_difficulty=4,
        safety_car_probability=0.20,
        weather_profile="dry",
        rain_probability=0.10,
        hard_compound="C1",
        medium_compound="C2",
        soft_compound="C3",
    ),
    Circuit(
        code="spielberg",
        name="Red Bull Ring",
        country="Austria",
        locality="Spielberg",
        length_metres=4318,
        race_laps=71,
        calendar_order=10,
        race_date_2026=date(2026, 6, 28),
        weekend_format_2026="standard",
        base_lap_seconds=68.0,
        engine_power_weight=0.80,
        downforce_weight=0.65,
        aero_efficiency_weight=0.70,
        mechanical_grip_weight=0.75,
        tyre_management_weight=0.70,
        reliability_weight=0.70,
        tyre_severity=3,
        overtaking_difficulty=2,
        safety_car_probability=0.35,
        weather_profile="variable",
        rain_probability=0.30,
        hard_compound="C3",
        medium_compound="C4",
        soft_compound="C5",
    ),
    Circuit(
        code="silverstone",
        name="Silverstone Circuit",
        country="Gran Bretagna",
        locality="Silverstone",
        length_metres=5891,
        race_laps=52,
        calendar_order=11,
        race_date_2026=date(2026, 7, 5),
        weekend_format_2026="sprint",
        base_lap_seconds=90.0,
        engine_power_weight=0.75,
        downforce_weight=0.90,
        aero_efficiency_weight=0.75,
        mechanical_grip_weight=0.65,
        tyre_management_weight=0.85,
        reliability_weight=0.65,
        tyre_severity=5,
        overtaking_difficulty=2,
        safety_car_probability=0.30,
        weather_profile="variable",
        rain_probability=0.35,
        hard_compound="C1",
        medium_compound="C2",
        soft_compound="C3",
    ),
    Circuit(
        code="spa",
        name="Circuit de Spa-Francorchamps",
        country="Belgio",
        locality="Stavelot",
        length_metres=7004,
        race_laps=44,
        calendar_order=12,
        race_date_2026=date(2026, 7, 19),
        weekend_format_2026="standard",
        base_lap_seconds=107.0,
        engine_power_weight=0.85,
        downforce_weight=0.75,
        aero_efficiency_weight=0.85,
        mechanical_grip_weight=0.65,
        tyre_management_weight=0.75,
        reliability_weight=0.70,
        tyre_severity=4,
        overtaking_difficulty=1,
        safety_car_probability=0.45,
        weather_profile="wet",
        rain_probability=0.45,
        hard_compound="C2",
        medium_compound="C3",
        soft_compound="C4",
    ),
    Circuit(
        code="hungaroring",
        name="Hungaroring",
        country="Ungheria",
        locality="Mogyorod",
        length_metres=4381,
        race_laps=70,
        calendar_order=13,
        race_date_2026=date(2026, 7, 26),
        weekend_format_2026="standard",
        base_lap_seconds=80.0,
        engine_power_weight=0.55,
        downforce_weight=0.90,
        aero_efficiency_weight=0.50,
        mechanical_grip_weight=0.85,
        tyre_management_weight=0.75,
        reliability_weight=0.70,
        tyre_severity=3,
        overtaking_difficulty=4,
        safety_car_probability=0.30,
        weather_profile="dry",
        rain_probability=0.20,
        hard_compound="C3",
        medium_compound="C4",
        soft_compound="C5",
    ),
    Circuit(
        code="zandvoort",
        name="Circuit Zandvoort",
        country="Paesi Bassi",
        locality="Zandvoort",
        length_metres=4259,
        race_laps=72,
        calendar_order=14,
        race_date_2026=date(2026, 8, 23),
        weekend_format_2026="sprint",
        base_lap_seconds=75.0,
        engine_power_weight=0.60,
        downforce_weight=0.90,
        aero_efficiency_weight=0.60,
        mechanical_grip_weight=0.80,
        tyre_management_weight=0.75,
        reliability_weight=0.65,
        tyre_severity=3,
        overtaking_difficulty=4,
        safety_car_probability=0.40,
        weather_profile="wet",
        rain_probability=0.40,
        hard_compound="C2",
        medium_compound="C3",
        soft_compound="C4",
    ),
    Circuit(
        code="monza",
        name="Autodromo Nazionale di Monza",
        country="Italia",
        locality="Monza",
        length_metres=5793,
        race_laps=53,
        calendar_order=15,
        race_date_2026=date(2026, 9, 6),
        weekend_format_2026="standard",
        base_lap_seconds=85.0,
        engine_power_weight=0.95,
        downforce_weight=0.45,
        aero_efficiency_weight=0.95,
        mechanical_grip_weight=0.60,
        tyre_management_weight=0.60,
        reliability_weight=0.75,
        tyre_severity=2,
        overtaking_difficulty=1,
        safety_car_probability=0.30,
        weather_profile="dry",
        rain_probability=0.15,
        hard_compound="C3",
        medium_compound="C4",
        soft_compound="C5",
    ),
    Circuit(
        code="madring",
        name="Madring",
        country="Spagna",
        locality="Madrid",
        length_metres=5474,
        race_laps=57,
        calendar_order=16,
        race_date_2026=date(2026, 9, 13),
        weekend_format_2026="standard",
        base_lap_seconds=95.0,
        engine_power_weight=0.70,
        downforce_weight=0.75,
        aero_efficiency_weight=0.70,
        mechanical_grip_weight=0.80,
        tyre_management_weight=0.70,
        reliability_weight=0.65,
        tyre_severity=3,
        overtaking_difficulty=3,
        safety_car_probability=0.50,
        weather_profile="dry",
        rain_probability=0.15,
        hard_compound="C2",
        medium_compound="C3",
        soft_compound="C4",
    ),
    Circuit(
        code="baku",
        name="Baku City Circuit",
        country="Azerbaigian",
        locality="Baku",
        length_metres=6003,
        race_laps=51,
        calendar_order=17,
        race_date_2026=date(2026, 9, 27),
        weekend_format_2026="standard",
        base_lap_seconds=105.0,
        engine_power_weight=0.90,
        downforce_weight=0.60,
        aero_efficiency_weight=0.85,
        mechanical_grip_weight=0.75,
        tyre_management_weight=0.60,
        reliability_weight=0.70,
        tyre_severity=2,
        overtaking_difficulty=2,
        safety_car_probability=0.60,
        weather_profile="dry",
        rain_probability=0.10,
        hard_compound="C3",
        medium_compound="C4",
        soft_compound="C5",
    ),
    Circuit(
        code="marina_bay",
        name="Marina Bay Street Circuit",
        country="Singapore",
        locality="Singapore",
        length_metres=4940,
        race_laps=62,
        calendar_order=18,
        race_date_2026=date(2026, 10, 11),
        weekend_format_2026="sprint",
        base_lap_seconds=97.0,
        engine_power_weight=0.55,
        downforce_weight=0.90,
        aero_efficiency_weight=0.50,
        mechanical_grip_weight=0.90,
        tyre_management_weight=0.70,
        reliability_weight=0.85,
        tyre_severity=3,
        overtaking_difficulty=4,
        safety_car_probability=0.70,
        weather_profile="wet",
        rain_probability=0.40,
        hard_compound="C3",
        medium_compound="C4",
        soft_compound="C5",
    ),
    Circuit(
        code="austin",
        name="Circuit of the Americas",
        country="Stati Uniti",
        locality="Austin",
        length_metres=5513,
        race_laps=56,
        calendar_order=19,
        race_date_2026=date(2026, 10, 25),
        weekend_format_2026="standard",
        base_lap_seconds=96.0,
        engine_power_weight=0.75,
        downforce_weight=0.80,
        aero_efficiency_weight=0.70,
        mechanical_grip_weight=0.75,
        tyre_management_weight=0.80,
        reliability_weight=0.65,
        tyre_severity=4,
        overtaking_difficulty=2,
        safety_car_probability=0.35,
        weather_profile="variable",
        rain_probability=0.20,
        hard_compound="C2",
        medium_compound="C3",
        soft_compound="C4",
    ),
    Circuit(
        code="citta_del_messico",
        name="Autodromo Hermanos Rodriguez",
        country="Messico",
        locality="Citta del Messico",
        length_metres=4304,
        race_laps=71,
        calendar_order=20,
        race_date_2026=date(2026, 11, 1),
        weekend_format_2026="standard",
        base_lap_seconds=81.0,
        engine_power_weight=0.70,
        downforce_weight=0.85,
        aero_efficiency_weight=0.55,
        mechanical_grip_weight=0.75,
        tyre_management_weight=0.70,
        reliability_weight=0.85,
        tyre_severity=2,
        overtaking_difficulty=3,
        safety_car_probability=0.40,
        weather_profile="variable",
        rain_probability=0.25,
        hard_compound="C3",
        medium_compound="C4",
        soft_compound="C5",
    ),
    Circuit(
        code="interlagos",
        name="Autodromo Jose Carlos Pace",
        country="Brasile",
        locality="San Paolo",
        length_metres=4309,
        race_laps=71,
        calendar_order=21,
        race_date_2026=date(2026, 11, 8),
        weekend_format_2026="standard",
        base_lap_seconds=75.0,
        engine_power_weight=0.75,
        downforce_weight=0.75,
        aero_efficiency_weight=0.70,
        mechanical_grip_weight=0.75,
        tyre_management_weight=0.75,
        reliability_weight=0.70,
        tyre_severity=3,
        overtaking_difficulty=2,
        safety_car_probability=0.45,
        weather_profile="wet",
        rain_probability=0.45,
        hard_compound="C2",
        medium_compound="C3",
        soft_compound="C4",
    ),
    Circuit(
        code="las_vegas",
        name="Las Vegas Strip Circuit",
        country="Stati Uniti",
        locality="Las Vegas",
        length_metres=6201,
        race_laps=50,
        calendar_order=22,
        race_date_2026=date(2026, 11, 21),
        weekend_format_2026="standard",
        base_lap_seconds=95.0,
        engine_power_weight=0.90,
        downforce_weight=0.50,
        aero_efficiency_weight=0.90,
        mechanical_grip_weight=0.70,
        tyre_management_weight=0.65,
        reliability_weight=0.65,
        tyre_severity=2,
        overtaking_difficulty=1,
        safety_car_probability=0.50,
        weather_profile="dry",
        rain_probability=0.05,
        hard_compound="C3",
        medium_compound="C4",
        soft_compound="C5",
    ),
    Circuit(
        code="lusail",
        name="Lusail International Circuit",
        country="Qatar",
        locality="Lusail",
        length_metres=5419,
        race_laps=57,
        calendar_order=23,
        race_date_2026=date(2026, 11, 29),
        weekend_format_2026="standard",
        base_lap_seconds=86.0,
        engine_power_weight=0.70,
        downforce_weight=0.85,
        aero_efficiency_weight=0.70,
        mechanical_grip_weight=0.65,
        tyre_management_weight=0.90,
        reliability_weight=0.75,
        tyre_severity=5,
        overtaking_difficulty=3,
        safety_car_probability=0.35,
        weather_profile="dry",
        rain_probability=0.05,
        hard_compound="C1",
        medium_compound="C2",
        soft_compound="C3",
    ),
    Circuit(
        code="yas_marina",
        name="Yas Marina Circuit",
        country="Emirati Arabi Uniti",
        locality="Abu Dhabi",
        length_metres=5281,
        race_laps=58,
        calendar_order=24,
        race_date_2026=date(2026, 12, 6),
        weekend_format_2026="standard",
        base_lap_seconds=88.0,
        engine_power_weight=0.75,
        downforce_weight=0.70,
        aero_efficiency_weight=0.70,
        mechanical_grip_weight=0.75,
        tyre_management_weight=0.70,
        reliability_weight=0.65,
        tyre_severity=2,
        overtaking_difficulty=3,
        safety_car_probability=0.35,
        weather_profile="dry",
        rain_probability=0.05,
        hard_compound="C3",
        medium_compound="C4",
        soft_compound="C5",
    ),
)

CIRCUITS_BY_CODE: dict[str, Circuit] = {circuit.code: circuit for circuit in CALENDAR_2026}


def circuit_by_code(code: str) -> Circuit:
    """Il circuito con il codice dato; KeyError con messaggio chiaro se assente."""
    try:
        return CIRCUITS_BY_CODE[code]
    except KeyError:
        raise KeyError(f"unknown circuit code: {code!r}") from None
